### ISSUE TITLE
Figure out roles/policies for deploying resources on AWS via act/terraform

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-on-demand#17]
Figure out roles/policies for deploying things on AWS

**Comment by pymonger** [comment]
# Assessment
In order to deploy and EKS cluster (via act + eksctl) and SPS (via terraform) from a management/deployer EC2 instance, an instance role needs to be created that aggregates the policies attached to the `MCP-SSM-CloudWatch` and `mcp-tenantOperator` roles. Those policies, as of 12/22/2022, are detailed below.

## AWS-managed polices
-  arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
- arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
- arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
- arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

## MCP-managed policies
- arn:aws:iam::${AWS::AccountId}:policy/mcp-tenantOperator
- arn:aws:iam::${AWS::AccountId}:policy/DatalakeKinesisPolicy
- arn:aws:iam::${AWS::AccountId}:policy/McpToolsAccessPolicy

## Permissions boundary policy
- arn:aws:iam::${AWS::AccountId}:policy/mcp-tenantOperator

These have been codified in the CloudFormation template that provisions the deployer/management EC2 instance:

https://github.com/unity-sds/unity-on-demand-cloudformation/blob/b17b793ad265e1d3e89f5fe0034bdfdc14849c91/templates/unity_deployer_instance-act.yaml#L83-L92
